# Generated by Django 4.0.4 on 2022-08-24 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_bonus_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(default='Aptech North Karachi', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hireDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
